{% set name = "astmonkey" %}
{% set version = "0.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/astmonkey-{{ version }}.tar.gz
  sha256: f82dbdd18a2d1810ef43782d3a29743bacd2b09422b8193a72a572b118c8cfb5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pydot
    - python >={{ python_min }}

test:
  imports:
    - astmonkey
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mutpy/astmonkey
  summary: astmonkey is a set of tools to play with Python AST.
  # Check with upstream to include license in package
  license_file: LICENSE
  license: Apache-2.0

extra:
  recipe-maintainers:
    - thewchan
